[xfi-guard]
enabled = true
backend = systemd
banaction = ufw
bantime = 604800
findtime = 600
maxretry = 1
filter = xfi-guard
port = ssh
journalmatch = _SYSTEMD_UNIT=xfi-guard.service
ignoreip = 127.0.0.1/8 ::1
